let comingSoonMovies = [
  {
    id: 1,
    name: "Shakeela - Hindi",
    language: "Hindi | TBA",
    category: "Romance",
    date: "12/25/2020",
    duration: "2 hrs 31 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/LzMcx7W/1.jpg",
    description:
      "A biographical drama film directed by Indrajit Lankesh, starring Richa Chadda in the lead role.",
  },
  {
    id: 2,
    name: "Vanguard ( U/A ) - English",
    language: "English | U/A",
    category: "Action",
    date: "12/25/2020",
    duration: "2 hrs 31 mins",
    actors: "Jackie Chan Yang Yang Lun Ai",
    director: "Stanley Tong",
    music: "Nathan Wang",
    img: "https://i.ibb.co/nPWFp8G/2.jpg",
    description:
      "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
  },
  {
    id: 3,
    name: "Operation JuJuPi - English",
    language: "English | TBA",
    category: "Thriller",
    date: "12/18/2020",
    duration: "1 hrs 50 mins",
    actors: "",
    director: "Arunkanth V",
    music: "Arunkanth V",
    img: "https://i.ibb.co/8mDTh5S/3.jpg",
    description: "Political Fantasy Thriller movie",
  },
  {
    id: 4,
    name: "Vaa - Tamil",
    language: "Tamil | TBA",
    category: "Romantic Comedy",
    date: "12/18/2020",
    duration: "1 hrs 28 mins",
    actors: "Arun Vijay Karthika Nair",
    director: "Shiva Gnanam",
    music: "S Thaman",
    img: "https://i.ibb.co/vzWq3Bh/4.jpg",
    description:
      "A youthful and upbeat entertainer with Arun Vijay and Karthika Nair teaming up to play the lead roles.",
  },
  {
    id: 5,
    name: "Aadhika vargam - Tamil",
    language: "Tamil | TBA",
    category: "Action Drama",
    date: "12/18/2020",
    duration: "2 hrs 14 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/gy4YPhg/5.jpg",
    description: "A film based on a true story",
  },
  {
    id: 6,
    name: "Ponniyin Selvan - Tamil",
    language: "Tamil | TBA",
    category: "Drama History",
    date: "11/19/2020",
    duration: "1 hrs 42 mins",
    actors: "",
    director: "Mani Ratnam",
    music: "",
    img: "https://i.ibb.co/dPn5LLz/6.jpg",
    description:
      "Ponniyin Selvan is an upcoming Indian Tamil-language historical drama film written and directed by Mani Ratnam and produced by Lyca Productions and Madras Talkies.",
  },
  {
    id: 7,
    name: "Pulanaivu - Tamil",
    language: "Tamil | TBA",
    category: "Drama",
    date: "11/13/2020 ",
    duration: "2 hrs 18 mins",
    actors: "Arvind Swami",
    director: "Santhosh P Jayakumar",
    music: "",
    img: "https://i.ibb.co/VQGXwzm/7.jpg",
    description:
      "A drama film directed by Santhosh P Jayakumar, starring Arvind Swami in a lead role.",
  },
  {
    id: 8,
    name: "Dhruva Natchathiram - Tamil",
    language: "Tamil | TBA",
    category: "Action Thriller",
    date: "4/27/2018 ",
    duration: "2 hrs 07 mins",
    actors:
      "Vikram Parthiepan Radikaa Sarathkumar Simran DD Ritu Varma Aishwarya Rajesh",
    director: "Gautham Menon",
    music: "AR Rahman",
    img: "https://i.ibb.co/XFjrwJ0/8.jpg",
    description:
      "An action thriller film directed by Gautham Menon, starring Vikram and Anu Emmanuel in the lead roles.",
  },
  {
    id: 9,
    name: "Ghost (A) - Hindi",
    language: "Hindi | A",
    category: "Horror Thriller",
    date: "1/19/2018 ",
    duration: "2 hrs 07 mins",
    actors: "Sanaya Irani",
    director: "Vikram Bhatt",
    music: "Arko Pravo Mukherjee",
    img: "https://i.ibb.co/ThZHNYm/9.jpg",
    description:
      "A horror film directed by Vikram Bhatt, starring Sanaya Irani in a lead role.",
  },
];

export default comingSoonMovies;
