let nowWatchingMovies = [
  {
    id: 1,
    name: "Wonder Woman 1984 -English",
    language: "English | U/A",
    category: "Action Adventure Fantasy",
    date: "12/25/2020",
    duration: "2 hrs 31 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/bWLSxz3/1.jpg",
    description:
      "Wonder Woman squares off against Maxwell Lord and the Cheetah, a villainess who possesses superhuman strength and agility.",
  },
  {
    id: 2,
    name: "Tenet - English",
    language: "English | U/A",
    category: "Action",
    date: "12/25/2020",
    duration: "2 hrs 31 mins",
    actors: "John David Washington Robert Pattinson Elizabeth Debicki",
    director: "Christopher Nolan",
    music: "",
    img: "https://i.ibb.co/JtZ7qn2/2.jpg",
    description:
      "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
  },
  {
    id: 3,
    name: "Sayonee - Hindi",
    language: "Hindi | U/A",
    category: "Action Musical Romance Thriller",
    date: "12/18/2020",
    duration: "1 hrs 50 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/CQwTtGH/3.jpg",
    description:
      "A romantic thriller movie directed by Nitin Kumar Gupta and Abhay Singhal, starring Tanmay Ssingh, Musskan Sethi, Rahul Roy and Yograj Singh in the lead roles.",
  },
  {
    id: 4,
    name: "Revolver - Bengali",
    language: "Bengali | U",
    category: "Thriller",
    date: "12/18/2020",
    duration: "1 hrs 28 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/RQ65K3G/4.jpg",
    description: "A thriller movie directed by Sanjoy Bardhan.",
  },
  {
    id: 5,
    name: "Omprakash Zindabad - Hindi",
    language: "Hindi | TBA",
    category: "Drama",
    date: "12/18/2020",
    duration: "2 hrs 14 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/R7dRJyh/5.jpg",
    description:
      "A drama film directed by Ranjeet Gupta, starring Om Puri in the lead role.",
  },
  {
    id: 6,
    name: "Chobiyal - Bengali",
    language: "Bengali | TBA",
    category: "Drama ",
    date: "11/19/2020",
    duration: "1 hrs 42 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/Rvc0JDw/6.jpg",
    description:
      "Habol (Saswata) who is a photographer with a studio near a crematorium and is into dead body photography. Habol life changes when he falls in love with Labonyo played by Srabanti. They both start living together.",
  },
  {
    id: 7,
    name: "Switzerland (U) - Bengali",
    language: "Bengali | U",
    category: "Drama",
    date: "11/13/2020 ",
    duration: "2 hrs 18 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/VW37qDy/7.jpg",
    description:
      "A middle-class family aims to travel to Switzerland but not able to afford the trip due to a financial crisis. However, the family deals with ample struggles and challenges to fulfill their wish.",
  },
  {
    id: 8,
    name: "Guptodhoner Sondhane(U)",
    language: "Bengali | U",
    category: "Drama ",
    date: "4/27/2018 ",
    duration: "2 hrs 07 mins",
    actors: "Abir Chatterjee Arjun Chakraborty Isha Saha",
    director: "Dhrubo Bandopadhyay",
    music: "Bickram Ghosh",
    img: "https://i.ibb.co/80TQwcG/8.jpg",
    description:
      "A drama film directed by Dhrubo Banerjee, starring Abir Chatterjee, Arjun Chakraborty and Isha Saha in the lead roles.",
  },
  {
    id: 9,
    name: "Asche Abar Shabor - Bengali",
    language: "Bengali | A",
    category: "Thriller ",
    date: "1/19/2018 ",
    duration: "2 hrs 07 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/8NqH7nG/9.jpg",
    description:
      "After two brutal and inhumane incidents of rape and murder in Kolkata and Chandernagore come to light, Shabor Dasgupta and his team try to nab the culprits. What they unravel is a tale of extreme lust, hate, and selfishness.",
  },
  {
    id: 10,
    name: "Indoo Ki Jawani ( U/A ) - Hindi",
    language: "Hindi | U/A",
    category: "Comedy Drama ",
    date: "12/11/2020 ",
    duration: "1 hrs 59 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/x7mTPvy/10.jpg",
    description:
      "This comedy-drama revolves around Indoo, a young, spirited girl from Ghaziabad who experiments with dating apps and often ends up in comical situations.",
  },
  {
    id: 11,
    name: "Byomkesh Gowtro (U/A) - Bengali",
    language: "Bengali | U/A",
    category: "Drama ",
    date: "10/12/2018",
    duration: "2 hrs 15 mins",
    actors: "Abir Chatterjee Sohini Sarkar",
    director: " Arindam Sil",
    music: "Bickram Ghosh",
    img: "https://i.ibb.co/kQ6kBJM/11.jpg",
    description:
      "Satyakam, the son of a business magnate who approaches Byomkesh for help is found dead soon a legendary detective head to Mussoorie to unravel the mystery behind the murde",
  },
  {
    id: 12,
    name: "Eagoler Chokh",
    language: "Bengali | A",
    category: "Drama Musical Thriller",
    date: "12/25/2020",
    duration: "2 hrs 31 mins",
    actors: "",
    director: "",
    music: "",
    img: "https://i.ibb.co/H46S5Pr/12.jpg",
    description:
      "A drama thriller film directed by Yuval Adler, starring Noomi Rapace, Joel Kinnaman and Chris Messina in the lead roles.",
  },
];

export default nowWatchingMovies;
